//
// CarSharingCar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class CarSharingCar: Codable, Hashable {

    public var address: Address?
    public var dataType: DataType?
    public var description: String?
    public var id: String?
    public var imageId: String?
    public var location: Geometry?
    public var name: String?
    public var networkId: String?
    public var operatorId: String?
    public var removed: Bool?
    public var timestamp: Date?
    public var trafficType: TrafficType?
    public var uri: String?
    public var data: DoraData?
    public var booking: ExternalReference?
    public var state: StateType?
    public var region: String?
    public var expectedRange: ValueInMeter?
    public var fuelLevel: ValueInPercent?
    public var fuelType: FuelType?
    public var registrationNumber: String?
    public var bagguages: Int?
    public var batteryCapacity: ValueInKilowattHour?
    public var carClass: String?
    public var carModel: String?
    public var exterior: RatingType?
    public var interior: RatingType?
    public var length: ValueInMeter?
    public var mileage: ValueInMeter?
    public var seats: Int?
    public var technical: RatingType?
    public var transmission: TransmissionType?

    public init(address: Address? = nil, dataType: DataType? = nil, description: String? = nil, id: String? = nil, imageId: String? = nil, location: Geometry? = nil, name: String? = nil, networkId: String? = nil, operatorId: String? = nil, removed: Bool? = nil, timestamp: Date? = nil, trafficType: TrafficType? = nil, uri: String? = nil, data: DoraData? = nil, booking: ExternalReference? = nil, state: StateType? = nil, region: String? = nil, expectedRange: ValueInMeter? = nil, fuelLevel: ValueInPercent? = nil, fuelType: FuelType? = nil, registrationNumber: String? = nil, bagguages: Int? = nil, batteryCapacity: ValueInKilowattHour? = nil, carClass: String? = nil, carModel: String? = nil, exterior: RatingType? = nil, interior: RatingType? = nil, length: ValueInMeter? = nil, mileage: ValueInMeter? = nil, seats: Int? = nil, technical: RatingType? = nil, transmission: TransmissionType? = nil) {
        self.address = address
        self.dataType = dataType
        self.description = description
        self.id = id
        self.imageId = imageId
        self.location = location
        self.name = name
        self.networkId = networkId
        self.operatorId = operatorId
        self.removed = removed
        self.timestamp = timestamp
        self.trafficType = trafficType
        self.uri = uri
        self.data = data
        self.booking = booking
        self.state = state
        self.region = region
        self.expectedRange = expectedRange
        self.fuelLevel = fuelLevel
        self.fuelType = fuelType
        self.registrationNumber = registrationNumber
        self.bagguages = bagguages
        self.batteryCapacity = batteryCapacity
        self.carClass = carClass
        self.carModel = carModel
        self.exterior = exterior
        self.interior = interior
        self.length = length
        self.mileage = mileage
        self.seats = seats
        self.technical = technical
        self.transmission = transmission
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case dataType
        case description
        case id
        case imageId
        case location
        case name
        case networkId
        case operatorId
        case removed
        case timestamp
        case trafficType
        case uri
        case data
        case booking
        case state
        case region
        case expectedRange
        case fuelLevel
        case fuelType
        case registrationNumber
        case bagguages
        case batteryCapacity
        case carClass
        case carModel
        case exterior
        case interior
        case length
        case mileage
        case seats
        case technical
        case transmission
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(dataType, forKey: .dataType)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(imageId, forKey: .imageId)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(networkId, forKey: .networkId)
        try container.encodeIfPresent(operatorId, forKey: .operatorId)
        try container.encodeIfPresent(removed, forKey: .removed)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(trafficType, forKey: .trafficType)
        try container.encodeIfPresent(uri, forKey: .uri)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(booking, forKey: .booking)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(region, forKey: .region)
        try container.encodeIfPresent(expectedRange, forKey: .expectedRange)
        try container.encodeIfPresent(fuelLevel, forKey: .fuelLevel)
        try container.encodeIfPresent(fuelType, forKey: .fuelType)
        try container.encodeIfPresent(registrationNumber, forKey: .registrationNumber)
        try container.encodeIfPresent(bagguages, forKey: .bagguages)
        try container.encodeIfPresent(batteryCapacity, forKey: .batteryCapacity)
        try container.encodeIfPresent(carClass, forKey: .carClass)
        try container.encodeIfPresent(carModel, forKey: .carModel)
        try container.encodeIfPresent(exterior, forKey: .exterior)
        try container.encodeIfPresent(interior, forKey: .interior)
        try container.encodeIfPresent(length, forKey: .length)
        try container.encodeIfPresent(mileage, forKey: .mileage)
        try container.encodeIfPresent(seats, forKey: .seats)
        try container.encodeIfPresent(technical, forKey: .technical)
        try container.encodeIfPresent(transmission, forKey: .transmission)
    }

    public static func == (lhs: CarSharingCar, rhs: CarSharingCar) -> Bool {
        lhs.address == rhs.address &&
        lhs.dataType == rhs.dataType &&
        lhs.description == rhs.description &&
        lhs.id == rhs.id &&
        lhs.imageId == rhs.imageId &&
        lhs.location == rhs.location &&
        lhs.name == rhs.name &&
        lhs.networkId == rhs.networkId &&
        lhs.operatorId == rhs.operatorId &&
        lhs.removed == rhs.removed &&
        lhs.timestamp == rhs.timestamp &&
        lhs.trafficType == rhs.trafficType &&
        lhs.uri == rhs.uri &&
        lhs.data == rhs.data &&
        lhs.booking == rhs.booking &&
        lhs.state == rhs.state &&
        lhs.region == rhs.region &&
        lhs.expectedRange == rhs.expectedRange &&
        lhs.fuelLevel == rhs.fuelLevel &&
        lhs.fuelType == rhs.fuelType &&
        lhs.registrationNumber == rhs.registrationNumber &&
        lhs.bagguages == rhs.bagguages &&
        lhs.batteryCapacity == rhs.batteryCapacity &&
        lhs.carClass == rhs.carClass &&
        lhs.carModel == rhs.carModel &&
        lhs.exterior == rhs.exterior &&
        lhs.interior == rhs.interior &&
        lhs.length == rhs.length &&
        lhs.mileage == rhs.mileage &&
        lhs.seats == rhs.seats &&
        lhs.technical == rhs.technical &&
        lhs.transmission == rhs.transmission
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(address?.hashValue)
        hasher.combine(dataType?.hashValue)
        hasher.combine(description?.hashValue)
        hasher.combine(id?.hashValue)
        hasher.combine(imageId?.hashValue)
        hasher.combine(location?.hashValue)
        hasher.combine(name?.hashValue)
        hasher.combine(networkId?.hashValue)
        hasher.combine(operatorId?.hashValue)
        hasher.combine(removed?.hashValue)
        hasher.combine(timestamp?.hashValue)
        hasher.combine(trafficType?.hashValue)
        hasher.combine(uri?.hashValue)
        hasher.combine(data?.hashValue)
        hasher.combine(booking?.hashValue)
        hasher.combine(state?.hashValue)
        hasher.combine(region?.hashValue)
        hasher.combine(expectedRange?.hashValue)
        hasher.combine(fuelLevel?.hashValue)
        hasher.combine(fuelType?.hashValue)
        hasher.combine(registrationNumber?.hashValue)
        hasher.combine(bagguages?.hashValue)
        hasher.combine(batteryCapacity?.hashValue)
        hasher.combine(carClass?.hashValue)
        hasher.combine(carModel?.hashValue)
        hasher.combine(exterior?.hashValue)
        hasher.combine(interior?.hashValue)
        hasher.combine(length?.hashValue)
        hasher.combine(mileage?.hashValue)
        hasher.combine(seats?.hashValue)
        hasher.combine(technical?.hashValue)
        hasher.combine(transmission?.hashValue)
        
    }
}

