//
// DetailState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DetailState: String, Codable, CaseIterable {
    case high = "HIGH"
    case low = "LOW"
    case medium = "MEDIUM"
}
