//
// ExternalReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class ExternalReference: Codable, Hashable {

    public var method: HttpMethod?
    public var url: String?

    public init(method: HttpMethod? = nil, url: String? = nil) {
        self.method = method
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case method
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(url, forKey: .url)
    }

    public static func == (lhs: ExternalReference, rhs: ExternalReference) -> Bool {
        lhs.method == rhs.method &&
        lhs.url == rhs.url
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(method?.hashValue)
        hasher.combine(url?.hashValue)
        
    }
}

