//
// GeometryPolygon.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class GeometryPolygon: Codable, Hashable {

    public var type: ModelType?
    public var coordinates: [[[Double]]]?

    public init(type: ModelType? = nil, coordinates: [[[Double]]]? = nil) {
        self.type = type
        self.coordinates = coordinates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case coordinates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(coordinates, forKey: .coordinates)
    }

    public static func == (lhs: GeometryPolygon, rhs: GeometryPolygon) -> Bool {
        lhs.type == rhs.type &&
        lhs.coordinates == rhs.coordinates
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(type?.hashValue)
        hasher.combine(coordinates?.hashValue)
        
    }
}

