//
// Geometry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class Geometry: Codable, Hashable {

    public var type: ModelType?
    public var coordinates: [Double]?
    public var x: Double?
    public var y: Double?

    public init(type: ModelType? = nil, coordinates: [Double]? = nil, x: Double? = nil, y: Double? = nil) {
        self.type = type
        self.coordinates = coordinates
        self.x = x
        self.y = y
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case coordinates
        case x
        case y
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(coordinates, forKey: .coordinates)
        try container.encodeIfPresent(x, forKey: .x)
        try container.encodeIfPresent(y, forKey: .y)
    }

    public static func == (lhs: Geometry, rhs: Geometry) -> Bool {
        lhs.type == rhs.type &&
        lhs.coordinates == rhs.coordinates &&
        lhs.x == rhs.x &&
        lhs.y == rhs.y
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(type?.hashValue)
        hasher.combine(coordinates?.hashValue)
        hasher.combine(x?.hashValue)
        hasher.combine(y?.hashValue)
        
    }
}

