//
// HttpMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum HttpMethod: String, Codable, CaseIterable {
    case delete = "delete"
    case `get` = "get"
    case post = "post"
    case put = "put"
}
