//
// IncidentProperty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum IncidentProperty: String, Codable, CaseIterable {
    case accessrestriction = "accessrestriction"
    case accident = "accident"
    case blockage = "blockage"
    case congestion = "congestion"
    case danger = "danger"
    case defective = "defective"
    case event = "event"
    case future = "future"
    case incident = "incident"
    case other = "other"
    case roadwork = "roadwork"
    case toll = "toll"
}
