//
// LotType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum LotType: String, Codable, CaseIterable {
    case bike = "bike"
    case bus = "bus"
    case carpark = "carPark"
    case handicapped = "handicapped"
    case lot = "lot"
    case other = "other"
    case parkandride = "parkAndRide"
    case parkingspace = "parkingSpace"
    case undergroundcarpark = "undergroundCarPark"
    case unknown = "unknown"
    case zone = "zone"
}
