//
// StateType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum StateType: String, Codable, CaseIterable {
    case available = "available"
    case closed = "closed"
    case defective = "defective"
    case free = "free"
    case inservice = "inService"
    case inuse = "inUse"
    case occupied = "occupied"
    case other = "other"
    case outofservice = "outOfService"
    case reserved = "reserved"
    case unknown = "unknown"
}
