//
// TrafficType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TrafficType: String, Codable, CaseIterable {
    case aircraft = "aircraft"
    case bike = "bike"
    case bus = "bus"
    case car = "car"
    case citytrain = "cityTrain"
    case coach = "coach"
    case ebike = "eBike"
    case ferry = "ferry"
    case metro = "metro"
    case motorbike = "motorbike"
    case other = "other"
    case regiotrain = "regioTrain"
    case scooter = "scooter"
    case train = "train"
    case tram = "tram"
    case unknown = "unknown"
    case walk = "walk"
    case wheelchair = "wheelchair"
}
