//
// TransmissionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TransmissionType: String, Codable, CaseIterable {
    case automatic = "automatic"
    case manual = "manual"
    case unknown = "unknown"
}
