//
// Type1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Type1: String, Codable, CaseIterable {
    case geometryCollection = "GeometryCollection"
    case lineString = "LineString"
    case multiLineString = "MultiLineString"
    case multiPoint = "MultiPoint"
    case multiPolygon = "MultiPolygon"
    case point = "Point"
    case polygon = "Polygon"
}
