//
// Unit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Unit: String, Codable, CaseIterable {
    case ampere = "ampere"
    case degree = "degree"
    case degreecelsius = "degreeCelsius"
    case euro = "euro"
    case gram = "gram"
    case gramperkilometer = "gramPerKilometer"
    case hectopascal = "hectoPascal"
    case kilometerperhour = "kilometerPerHour"
    case kilowatthour = "kilowatthour"
    case literpersquaremeter = "literPerSquaremeter"
    case meter = "meter"
    case meterpersecond = "meterPerSecond"
    case minute = "minute"
    case percentage = "percentage"
    case second = "second"
    case volt = "volt"
    case watt = "watt"
}
